//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAAD_TransactionChecker.HaaD {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.shafafiya.org/v2/", ConfigurationName="HaaD.WebservicesSoap")]
    public interface WebservicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/UploadTransaction", ReplyAction="*")]
        HAAD_TransactionChecker.HaaD.UploadTransactionResponse UploadTransaction(HAAD_TransactionChecker.HaaD.UploadTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/UploadTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<HAAD_TransactionChecker.HaaD.UploadTransactionResponse> UploadTransactionAsync(HAAD_TransactionChecker.HaaD.UploadTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/GetNewTransactions", ReplyAction="*")]
        HAAD_TransactionChecker.HaaD.GetNewTransactionsResponse GetNewTransactions(HAAD_TransactionChecker.HaaD.GetNewTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/GetNewTransactions", ReplyAction="*")]
        System.Threading.Tasks.Task<HAAD_TransactionChecker.HaaD.GetNewTransactionsResponse> GetNewTransactionsAsync(HAAD_TransactionChecker.HaaD.GetNewTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/DownloadTransactionFile", ReplyAction="*")]
        HAAD_TransactionChecker.HaaD.DownloadTransactionFileResponse DownloadTransactionFile(HAAD_TransactionChecker.HaaD.DownloadTransactionFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/DownloadTransactionFile", ReplyAction="*")]
        System.Threading.Tasks.Task<HAAD_TransactionChecker.HaaD.DownloadTransactionFileResponse> DownloadTransactionFileAsync(HAAD_TransactionChecker.HaaD.DownloadTransactionFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/SearchTransactions", ReplyAction="*")]
        HAAD_TransactionChecker.HaaD.SearchTransactionsResponse SearchTransactions(HAAD_TransactionChecker.HaaD.SearchTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/SearchTransactions", ReplyAction="*")]
        System.Threading.Tasks.Task<HAAD_TransactionChecker.HaaD.SearchTransactionsResponse> SearchTransactionsAsync(HAAD_TransactionChecker.HaaD.SearchTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/SetTransactionDownloaded", ReplyAction="*")]
        HAAD_TransactionChecker.HaaD.SetTransactionDownloadedResponse SetTransactionDownloaded(HAAD_TransactionChecker.HaaD.SetTransactionDownloadedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/SetTransactionDownloaded", ReplyAction="*")]
        System.Threading.Tasks.Task<HAAD_TransactionChecker.HaaD.SetTransactionDownloadedResponse> SetTransactionDownloadedAsync(HAAD_TransactionChecker.HaaD.SetTransactionDownloadedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/GetPrescriptions", ReplyAction="*")]
        HAAD_TransactionChecker.HaaD.GetPrescriptionsResponse GetPrescriptions(HAAD_TransactionChecker.HaaD.GetPrescriptionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/GetPrescriptions", ReplyAction="*")]
        System.Threading.Tasks.Task<HAAD_TransactionChecker.HaaD.GetPrescriptionsResponse> GetPrescriptionsAsync(HAAD_TransactionChecker.HaaD.GetPrescriptionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/AddDRGToEClaim", ReplyAction="*")]
        HAAD_TransactionChecker.HaaD.AddDRGToEClaimResponse AddDRGToEClaim(HAAD_TransactionChecker.HaaD.AddDRGToEClaimRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/AddDRGToEClaim", ReplyAction="*")]
        System.Threading.Tasks.Task<HAAD_TransactionChecker.HaaD.AddDRGToEClaimResponse> AddDRGToEClaimAsync(HAAD_TransactionChecker.HaaD.AddDRGToEClaimRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/CheckForNewPriorAuthorizationTransactions", ReplyAction="*")]
        HAAD_TransactionChecker.HaaD.CheckForNewPriorAuthorizationTransactionsResponse CheckForNewPriorAuthorizationTransactions(HAAD_TransactionChecker.HaaD.CheckForNewPriorAuthorizationTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/CheckForNewPriorAuthorizationTransactions", ReplyAction="*")]
        System.Threading.Tasks.Task<HAAD_TransactionChecker.HaaD.CheckForNewPriorAuthorizationTransactionsResponse> CheckForNewPriorAuthorizationTransactionsAsync(HAAD_TransactionChecker.HaaD.CheckForNewPriorAuthorizationTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/GetNewPriorAuthorizationTransactions", ReplyAction="*")]
        HAAD_TransactionChecker.HaaD.GetNewPriorAuthorizationTransactionsResponse GetNewPriorAuthorizationTransactions(HAAD_TransactionChecker.HaaD.GetNewPriorAuthorizationTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/GetNewPriorAuthorizationTransactions", ReplyAction="*")]
        System.Threading.Tasks.Task<HAAD_TransactionChecker.HaaD.GetNewPriorAuthorizationTransactionsResponse> GetNewPriorAuthorizationTransactionsAsync(HAAD_TransactionChecker.HaaD.GetNewPriorAuthorizationTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/GetDRGDetails", ReplyAction="*")]
        HAAD_TransactionChecker.HaaD.GetDRGDetailsResponse GetDRGDetails(HAAD_TransactionChecker.HaaD.GetDRGDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.shafafiya.org/v2/GetDRGDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<HAAD_TransactionChecker.HaaD.GetDRGDetailsResponse> GetDRGDetailsAsync(HAAD_TransactionChecker.HaaD.GetDRGDetailsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadTransaction", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public HAAD_TransactionChecker.HaaD.UploadTransactionRequestBody Body;
        
        public UploadTransactionRequest() {
        }
        
        public UploadTransactionRequest(HAAD_TransactionChecker.HaaD.UploadTransactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class UploadTransactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] fileContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string fileName;
        
        public UploadTransactionRequestBody() {
        }
        
        public UploadTransactionRequestBody(string login, string pwd, byte[] fileContent, string fileName) {
            this.login = login;
            this.pwd = pwd;
            this.fileContent = fileContent;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadTransactionResponse", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public HAAD_TransactionChecker.HaaD.UploadTransactionResponseBody Body;
        
        public UploadTransactionResponse() {
        }
        
        public UploadTransactionResponse(HAAD_TransactionChecker.HaaD.UploadTransactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class UploadTransactionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UploadTransactionResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errorMessage;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] errorReport;
        
        public UploadTransactionResponseBody() {
        }
        
        public UploadTransactionResponseBody(int UploadTransactionResult, string errorMessage, byte[] errorReport) {
            this.UploadTransactionResult = UploadTransactionResult;
            this.errorMessage = errorMessage;
            this.errorReport = errorReport;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewTransactionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewTransactions", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public HAAD_TransactionChecker.HaaD.GetNewTransactionsRequestBody Body;
        
        public GetNewTransactionsRequest() {
        }
        
        public GetNewTransactionsRequest(HAAD_TransactionChecker.HaaD.GetNewTransactionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class GetNewTransactionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        public GetNewTransactionsRequestBody() {
        }
        
        public GetNewTransactionsRequestBody(string login, string pwd) {
            this.login = login;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewTransactionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewTransactionsResponse", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public HAAD_TransactionChecker.HaaD.GetNewTransactionsResponseBody Body;
        
        public GetNewTransactionsResponse() {
        }
        
        public GetNewTransactionsResponse(HAAD_TransactionChecker.HaaD.GetNewTransactionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class GetNewTransactionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetNewTransactionsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xmlTransactions;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string errorMessage;
        
        public GetNewTransactionsResponseBody() {
        }
        
        public GetNewTransactionsResponseBody(int GetNewTransactionsResult, string xmlTransactions, string errorMessage) {
            this.GetNewTransactionsResult = GetNewTransactionsResult;
            this.xmlTransactions = xmlTransactions;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadTransactionFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadTransactionFile", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public HAAD_TransactionChecker.HaaD.DownloadTransactionFileRequestBody Body;
        
        public DownloadTransactionFileRequest() {
        }
        
        public DownloadTransactionFileRequest(HAAD_TransactionChecker.HaaD.DownloadTransactionFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class DownloadTransactionFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fileId;
        
        public DownloadTransactionFileRequestBody() {
        }
        
        public DownloadTransactionFileRequestBody(string login, string pwd, string fileId) {
            this.login = login;
            this.pwd = pwd;
            this.fileId = fileId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadTransactionFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadTransactionFileResponse", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public HAAD_TransactionChecker.HaaD.DownloadTransactionFileResponseBody Body;
        
        public DownloadTransactionFileResponse() {
        }
        
        public DownloadTransactionFileResponse(HAAD_TransactionChecker.HaaD.DownloadTransactionFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class DownloadTransactionFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DownloadTransactionFileResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] file;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string errorMessage;
        
        public DownloadTransactionFileResponseBody() {
        }
        
        public DownloadTransactionFileResponseBody(int DownloadTransactionFileResult, string fileName, byte[] file, string errorMessage) {
            this.DownloadTransactionFileResult = DownloadTransactionFileResult;
            this.fileName = fileName;
            this.file = file;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchTransactionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchTransactions", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public HAAD_TransactionChecker.HaaD.SearchTransactionsRequestBody Body;
        
        public SearchTransactionsRequest() {
        }
        
        public SearchTransactionsRequest(HAAD_TransactionChecker.HaaD.SearchTransactionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class SearchTransactionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int direction;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string callerLicense;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ePartner;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int transactionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int transactionStatus;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string transactionFileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string transactionFromDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string transactionToDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int minRecordCount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public int maxRecordCount;
        
        public SearchTransactionsRequestBody() {
        }
        
        public SearchTransactionsRequestBody(string login, string pwd, int direction, string callerLicense, string ePartner, int transactionID, int transactionStatus, string transactionFileName, string transactionFromDate, string transactionToDate, int minRecordCount, int maxRecordCount) {
            this.login = login;
            this.pwd = pwd;
            this.direction = direction;
            this.callerLicense = callerLicense;
            this.ePartner = ePartner;
            this.transactionID = transactionID;
            this.transactionStatus = transactionStatus;
            this.transactionFileName = transactionFileName;
            this.transactionFromDate = transactionFromDate;
            this.transactionToDate = transactionToDate;
            this.minRecordCount = minRecordCount;
            this.maxRecordCount = maxRecordCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchTransactionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchTransactionsResponse", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public HAAD_TransactionChecker.HaaD.SearchTransactionsResponseBody Body;
        
        public SearchTransactionsResponse() {
        }
        
        public SearchTransactionsResponse(HAAD_TransactionChecker.HaaD.SearchTransactionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class SearchTransactionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SearchTransactionsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string foundTransactions;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string errorMessage;
        
        public SearchTransactionsResponseBody() {
        }
        
        public SearchTransactionsResponseBody(int SearchTransactionsResult, string foundTransactions, string errorMessage) {
            this.SearchTransactionsResult = SearchTransactionsResult;
            this.foundTransactions = foundTransactions;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetTransactionDownloadedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetTransactionDownloaded", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public HAAD_TransactionChecker.HaaD.SetTransactionDownloadedRequestBody Body;
        
        public SetTransactionDownloadedRequest() {
        }
        
        public SetTransactionDownloadedRequest(HAAD_TransactionChecker.HaaD.SetTransactionDownloadedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class SetTransactionDownloadedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fileId;
        
        public SetTransactionDownloadedRequestBody() {
        }
        
        public SetTransactionDownloadedRequestBody(string login, string pwd, string fileId) {
            this.login = login;
            this.pwd = pwd;
            this.fileId = fileId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetTransactionDownloadedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetTransactionDownloadedResponse", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public HAAD_TransactionChecker.HaaD.SetTransactionDownloadedResponseBody Body;
        
        public SetTransactionDownloadedResponse() {
        }
        
        public SetTransactionDownloadedResponse(HAAD_TransactionChecker.HaaD.SetTransactionDownloadedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class SetTransactionDownloadedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SetTransactionDownloadedResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errorMessage;
        
        public SetTransactionDownloadedResponseBody() {
        }
        
        public SetTransactionDownloadedResponseBody(int SetTransactionDownloadedResult, string errorMessage) {
            this.SetTransactionDownloadedResult = SetTransactionDownloadedResult;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPrescriptionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPrescriptions", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public HAAD_TransactionChecker.HaaD.GetPrescriptionsRequestBody Body;
        
        public GetPrescriptionsRequest() {
        }
        
        public GetPrescriptionsRequest(HAAD_TransactionChecker.HaaD.GetPrescriptionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class GetPrescriptionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string payerID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string memberID;
        
        public GetPrescriptionsRequestBody() {
        }
        
        public GetPrescriptionsRequestBody(string login, string pwd, string payerID, string memberID) {
            this.login = login;
            this.pwd = pwd;
            this.payerID = payerID;
            this.memberID = memberID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPrescriptionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPrescriptionsResponse", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public HAAD_TransactionChecker.HaaD.GetPrescriptionsResponseBody Body;
        
        public GetPrescriptionsResponse() {
        }
        
        public GetPrescriptionsResponse(HAAD_TransactionChecker.HaaD.GetPrescriptionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class GetPrescriptionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetPrescriptionsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] prescription;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string errorMessage;
        
        public GetPrescriptionsResponseBody() {
        }
        
        public GetPrescriptionsResponseBody(int GetPrescriptionsResult, byte[] prescription, string errorMessage) {
            this.GetPrescriptionsResult = GetPrescriptionsResult;
            this.prescription = prescription;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDRGToEClaimRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDRGToEClaim", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public HAAD_TransactionChecker.HaaD.AddDRGToEClaimRequestBody Body;
        
        public AddDRGToEClaimRequest() {
        }
        
        public AddDRGToEClaimRequest(HAAD_TransactionChecker.HaaD.AddDRGToEClaimRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class AddDRGToEClaimRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] originalFileContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string originalFileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal baseRate;
        
        public AddDRGToEClaimRequestBody() {
        }
        
        public AddDRGToEClaimRequestBody(string login, string pwd, byte[] originalFileContent, string originalFileName, decimal baseRate) {
            this.login = login;
            this.pwd = pwd;
            this.originalFileContent = originalFileContent;
            this.originalFileName = originalFileName;
            this.baseRate = baseRate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDRGToEClaimResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDRGToEClaimResponse", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public HAAD_TransactionChecker.HaaD.AddDRGToEClaimResponseBody Body;
        
        public AddDRGToEClaimResponse() {
        }
        
        public AddDRGToEClaimResponse(HAAD_TransactionChecker.HaaD.AddDRGToEClaimResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class AddDRGToEClaimResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddDRGToEClaimResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] drgFileContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string drgFileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] auditFileContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public byte[] reportFileContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string errorMessage;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public byte[] errorReport;
        
        public AddDRGToEClaimResponseBody() {
        }
        
        public AddDRGToEClaimResponseBody(int AddDRGToEClaimResult, byte[] drgFileContent, string drgFileName, byte[] auditFileContent, byte[] reportFileContent, string errorMessage, byte[] errorReport) {
            this.AddDRGToEClaimResult = AddDRGToEClaimResult;
            this.drgFileContent = drgFileContent;
            this.drgFileName = drgFileName;
            this.auditFileContent = auditFileContent;
            this.reportFileContent = reportFileContent;
            this.errorMessage = errorMessage;
            this.errorReport = errorReport;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckForNewPriorAuthorizationTransactionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckForNewPriorAuthorizationTransactions", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public HAAD_TransactionChecker.HaaD.CheckForNewPriorAuthorizationTransactionsRequestBody Body;
        
        public CheckForNewPriorAuthorizationTransactionsRequest() {
        }
        
        public CheckForNewPriorAuthorizationTransactionsRequest(HAAD_TransactionChecker.HaaD.CheckForNewPriorAuthorizationTransactionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class CheckForNewPriorAuthorizationTransactionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        public CheckForNewPriorAuthorizationTransactionsRequestBody() {
        }
        
        public CheckForNewPriorAuthorizationTransactionsRequestBody(string login, string pwd) {
            this.login = login;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckForNewPriorAuthorizationTransactionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckForNewPriorAuthorizationTransactionsResponse", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public HAAD_TransactionChecker.HaaD.CheckForNewPriorAuthorizationTransactionsResponseBody Body;
        
        public CheckForNewPriorAuthorizationTransactionsResponse() {
        }
        
        public CheckForNewPriorAuthorizationTransactionsResponse(HAAD_TransactionChecker.HaaD.CheckForNewPriorAuthorizationTransactionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class CheckForNewPriorAuthorizationTransactionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CheckForNewPriorAuthorizationTransactionsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errorMessage;
        
        public CheckForNewPriorAuthorizationTransactionsResponseBody() {
        }
        
        public CheckForNewPriorAuthorizationTransactionsResponseBody(int CheckForNewPriorAuthorizationTransactionsResult, string errorMessage) {
            this.CheckForNewPriorAuthorizationTransactionsResult = CheckForNewPriorAuthorizationTransactionsResult;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewPriorAuthorizationTransactionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewPriorAuthorizationTransactions", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public HAAD_TransactionChecker.HaaD.GetNewPriorAuthorizationTransactionsRequestBody Body;
        
        public GetNewPriorAuthorizationTransactionsRequest() {
        }
        
        public GetNewPriorAuthorizationTransactionsRequest(HAAD_TransactionChecker.HaaD.GetNewPriorAuthorizationTransactionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class GetNewPriorAuthorizationTransactionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        public GetNewPriorAuthorizationTransactionsRequestBody() {
        }
        
        public GetNewPriorAuthorizationTransactionsRequestBody(string login, string pwd) {
            this.login = login;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewPriorAuthorizationTransactionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewPriorAuthorizationTransactionsResponse", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public HAAD_TransactionChecker.HaaD.GetNewPriorAuthorizationTransactionsResponseBody Body;
        
        public GetNewPriorAuthorizationTransactionsResponse() {
        }
        
        public GetNewPriorAuthorizationTransactionsResponse(HAAD_TransactionChecker.HaaD.GetNewPriorAuthorizationTransactionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class GetNewPriorAuthorizationTransactionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetNewPriorAuthorizationTransactionsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string foundTransactions;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string errorMessage;
        
        public GetNewPriorAuthorizationTransactionsResponseBody() {
        }
        
        public GetNewPriorAuthorizationTransactionsResponseBody(int GetNewPriorAuthorizationTransactionsResult, string foundTransactions, string errorMessage) {
            this.GetNewPriorAuthorizationTransactionsResult = GetNewPriorAuthorizationTransactionsResult;
            this.foundTransactions = foundTransactions;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDRGDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDRGDetails", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public HAAD_TransactionChecker.HaaD.GetDRGDetailsRequestBody Body;
        
        public GetDRGDetailsRequest() {
        }
        
        public GetDRGDetailsRequest(HAAD_TransactionChecker.HaaD.GetDRGDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class GetDRGDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string xmlClaimInput;
        
        public GetDRGDetailsRequestBody() {
        }
        
        public GetDRGDetailsRequestBody(string login, string pwd, string xmlClaimInput) {
            this.login = login;
            this.pwd = pwd;
            this.xmlClaimInput = xmlClaimInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDRGDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDRGDetailsResponse", Namespace="https://www.shafafiya.org/v2/", Order=0)]
        public HAAD_TransactionChecker.HaaD.GetDRGDetailsResponseBody Body;
        
        public GetDRGDetailsResponse() {
        }
        
        public GetDRGDetailsResponse(HAAD_TransactionChecker.HaaD.GetDRGDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.shafafiya.org/v2/")]
    public partial class GetDRGDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetDRGDetailsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xmlDRGDetails;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] auditFileContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] reportFileContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string errorMessage;
        
        public GetDRGDetailsResponseBody() {
        }
        
        public GetDRGDetailsResponseBody(int GetDRGDetailsResult, string xmlDRGDetails, byte[] auditFileContent, byte[] reportFileContent, string errorMessage) {
            this.GetDRGDetailsResult = GetDRGDetailsResult;
            this.xmlDRGDetails = xmlDRGDetails;
            this.auditFileContent = auditFileContent;
            this.reportFileContent = reportFileContent;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebservicesSoapChannel : HAAD_TransactionChecker.HaaD.WebservicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebservicesSoapClient : System.ServiceModel.ClientBase<HAAD_TransactionChecker.HaaD.WebservicesSoap>, HAAD_TransactionChecker.HaaD.WebservicesSoap {
        
        public WebservicesSoapClient() {
        }
        
        public WebservicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebservicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebservicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebservicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HAAD_TransactionChecker.HaaD.UploadTransactionResponse HAAD_TransactionChecker.HaaD.WebservicesSoap.UploadTransaction(HAAD_TransactionChecker.HaaD.UploadTransactionRequest request) {
            return base.Channel.UploadTransaction(request);
        }
        
        public int UploadTransaction(string login, string pwd, byte[] fileContent, string fileName, out string errorMessage, out byte[] errorReport) {
            HAAD_TransactionChecker.HaaD.UploadTransactionRequest inValue = new HAAD_TransactionChecker.HaaD.UploadTransactionRequest();
            inValue.Body = new HAAD_TransactionChecker.HaaD.UploadTransactionRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.fileContent = fileContent;
            inValue.Body.fileName = fileName;
            HAAD_TransactionChecker.HaaD.UploadTransactionResponse retVal = ((HAAD_TransactionChecker.HaaD.WebservicesSoap)(this)).UploadTransaction(inValue);
            errorMessage = retVal.Body.errorMessage;
            errorReport = retVal.Body.errorReport;
            return retVal.Body.UploadTransactionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HAAD_TransactionChecker.HaaD.UploadTransactionResponse> HAAD_TransactionChecker.HaaD.WebservicesSoap.UploadTransactionAsync(HAAD_TransactionChecker.HaaD.UploadTransactionRequest request) {
            return base.Channel.UploadTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<HAAD_TransactionChecker.HaaD.UploadTransactionResponse> UploadTransactionAsync(string login, string pwd, byte[] fileContent, string fileName) {
            HAAD_TransactionChecker.HaaD.UploadTransactionRequest inValue = new HAAD_TransactionChecker.HaaD.UploadTransactionRequest();
            inValue.Body = new HAAD_TransactionChecker.HaaD.UploadTransactionRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.fileContent = fileContent;
            inValue.Body.fileName = fileName;
            return ((HAAD_TransactionChecker.HaaD.WebservicesSoap)(this)).UploadTransactionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HAAD_TransactionChecker.HaaD.GetNewTransactionsResponse HAAD_TransactionChecker.HaaD.WebservicesSoap.GetNewTransactions(HAAD_TransactionChecker.HaaD.GetNewTransactionsRequest request) {
            return base.Channel.GetNewTransactions(request);
        }
        
        public int GetNewTransactions(string login, string pwd, out string xmlTransactions, out string errorMessage) {
            HAAD_TransactionChecker.HaaD.GetNewTransactionsRequest inValue = new HAAD_TransactionChecker.HaaD.GetNewTransactionsRequest();
            inValue.Body = new HAAD_TransactionChecker.HaaD.GetNewTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            HAAD_TransactionChecker.HaaD.GetNewTransactionsResponse retVal = ((HAAD_TransactionChecker.HaaD.WebservicesSoap)(this)).GetNewTransactions(inValue);
            xmlTransactions = retVal.Body.xmlTransactions;
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.GetNewTransactionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HAAD_TransactionChecker.HaaD.GetNewTransactionsResponse> HAAD_TransactionChecker.HaaD.WebservicesSoap.GetNewTransactionsAsync(HAAD_TransactionChecker.HaaD.GetNewTransactionsRequest request) {
            return base.Channel.GetNewTransactionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HAAD_TransactionChecker.HaaD.GetNewTransactionsResponse> GetNewTransactionsAsync(string login, string pwd) {
            HAAD_TransactionChecker.HaaD.GetNewTransactionsRequest inValue = new HAAD_TransactionChecker.HaaD.GetNewTransactionsRequest();
            inValue.Body = new HAAD_TransactionChecker.HaaD.GetNewTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            return ((HAAD_TransactionChecker.HaaD.WebservicesSoap)(this)).GetNewTransactionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HAAD_TransactionChecker.HaaD.DownloadTransactionFileResponse HAAD_TransactionChecker.HaaD.WebservicesSoap.DownloadTransactionFile(HAAD_TransactionChecker.HaaD.DownloadTransactionFileRequest request) {
            return base.Channel.DownloadTransactionFile(request);
        }
        
        public int DownloadTransactionFile(string login, string pwd, string fileId, out string fileName, out byte[] file, out string errorMessage) {
            HAAD_TransactionChecker.HaaD.DownloadTransactionFileRequest inValue = new HAAD_TransactionChecker.HaaD.DownloadTransactionFileRequest();
            inValue.Body = new HAAD_TransactionChecker.HaaD.DownloadTransactionFileRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.fileId = fileId;
            HAAD_TransactionChecker.HaaD.DownloadTransactionFileResponse retVal = ((HAAD_TransactionChecker.HaaD.WebservicesSoap)(this)).DownloadTransactionFile(inValue);
            fileName = retVal.Body.fileName;
            file = retVal.Body.file;
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.DownloadTransactionFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HAAD_TransactionChecker.HaaD.DownloadTransactionFileResponse> HAAD_TransactionChecker.HaaD.WebservicesSoap.DownloadTransactionFileAsync(HAAD_TransactionChecker.HaaD.DownloadTransactionFileRequest request) {
            return base.Channel.DownloadTransactionFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<HAAD_TransactionChecker.HaaD.DownloadTransactionFileResponse> DownloadTransactionFileAsync(string login, string pwd, string fileId) {
            HAAD_TransactionChecker.HaaD.DownloadTransactionFileRequest inValue = new HAAD_TransactionChecker.HaaD.DownloadTransactionFileRequest();
            inValue.Body = new HAAD_TransactionChecker.HaaD.DownloadTransactionFileRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.fileId = fileId;
            return ((HAAD_TransactionChecker.HaaD.WebservicesSoap)(this)).DownloadTransactionFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HAAD_TransactionChecker.HaaD.SearchTransactionsResponse HAAD_TransactionChecker.HaaD.WebservicesSoap.SearchTransactions(HAAD_TransactionChecker.HaaD.SearchTransactionsRequest request) {
            return base.Channel.SearchTransactions(request);
        }
        
        public int SearchTransactions(string login, string pwd, int direction, string callerLicense, string ePartner, int transactionID, int transactionStatus, string transactionFileName, string transactionFromDate, string transactionToDate, int minRecordCount, int maxRecordCount, out string foundTransactions, out string errorMessage) {
            HAAD_TransactionChecker.HaaD.SearchTransactionsRequest inValue = new HAAD_TransactionChecker.HaaD.SearchTransactionsRequest();
            inValue.Body = new HAAD_TransactionChecker.HaaD.SearchTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.direction = direction;
            inValue.Body.callerLicense = callerLicense;
            inValue.Body.ePartner = ePartner;
            inValue.Body.transactionID = transactionID;
            inValue.Body.transactionStatus = transactionStatus;
            inValue.Body.transactionFileName = transactionFileName;
            inValue.Body.transactionFromDate = transactionFromDate;
            inValue.Body.transactionToDate = transactionToDate;
            inValue.Body.minRecordCount = minRecordCount;
            inValue.Body.maxRecordCount = maxRecordCount;
            HAAD_TransactionChecker.HaaD.SearchTransactionsResponse retVal = ((HAAD_TransactionChecker.HaaD.WebservicesSoap)(this)).SearchTransactions(inValue);
            foundTransactions = retVal.Body.foundTransactions;
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.SearchTransactionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HAAD_TransactionChecker.HaaD.SearchTransactionsResponse> HAAD_TransactionChecker.HaaD.WebservicesSoap.SearchTransactionsAsync(HAAD_TransactionChecker.HaaD.SearchTransactionsRequest request) {
            return base.Channel.SearchTransactionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HAAD_TransactionChecker.HaaD.SearchTransactionsResponse> SearchTransactionsAsync(string login, string pwd, int direction, string callerLicense, string ePartner, int transactionID, int transactionStatus, string transactionFileName, string transactionFromDate, string transactionToDate, int minRecordCount, int maxRecordCount) {
            HAAD_TransactionChecker.HaaD.SearchTransactionsRequest inValue = new HAAD_TransactionChecker.HaaD.SearchTransactionsRequest();
            inValue.Body = new HAAD_TransactionChecker.HaaD.SearchTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.direction = direction;
            inValue.Body.callerLicense = callerLicense;
            inValue.Body.ePartner = ePartner;
            inValue.Body.transactionID = transactionID;
            inValue.Body.transactionStatus = transactionStatus;
            inValue.Body.transactionFileName = transactionFileName;
            inValue.Body.transactionFromDate = transactionFromDate;
            inValue.Body.transactionToDate = transactionToDate;
            inValue.Body.minRecordCount = minRecordCount;
            inValue.Body.maxRecordCount = maxRecordCount;
            return ((HAAD_TransactionChecker.HaaD.WebservicesSoap)(this)).SearchTransactionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HAAD_TransactionChecker.HaaD.SetTransactionDownloadedResponse HAAD_TransactionChecker.HaaD.WebservicesSoap.SetTransactionDownloaded(HAAD_TransactionChecker.HaaD.SetTransactionDownloadedRequest request) {
            return base.Channel.SetTransactionDownloaded(request);
        }
        
        public int SetTransactionDownloaded(string login, string pwd, string fileId, out string errorMessage) {
            HAAD_TransactionChecker.HaaD.SetTransactionDownloadedRequest inValue = new HAAD_TransactionChecker.HaaD.SetTransactionDownloadedRequest();
            inValue.Body = new HAAD_TransactionChecker.HaaD.SetTransactionDownloadedRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.fileId = fileId;
            HAAD_TransactionChecker.HaaD.SetTransactionDownloadedResponse retVal = ((HAAD_TransactionChecker.HaaD.WebservicesSoap)(this)).SetTransactionDownloaded(inValue);
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.SetTransactionDownloadedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HAAD_TransactionChecker.HaaD.SetTransactionDownloadedResponse> HAAD_TransactionChecker.HaaD.WebservicesSoap.SetTransactionDownloadedAsync(HAAD_TransactionChecker.HaaD.SetTransactionDownloadedRequest request) {
            return base.Channel.SetTransactionDownloadedAsync(request);
        }
        
        public System.Threading.Tasks.Task<HAAD_TransactionChecker.HaaD.SetTransactionDownloadedResponse> SetTransactionDownloadedAsync(string login, string pwd, string fileId) {
            HAAD_TransactionChecker.HaaD.SetTransactionDownloadedRequest inValue = new HAAD_TransactionChecker.HaaD.SetTransactionDownloadedRequest();
            inValue.Body = new HAAD_TransactionChecker.HaaD.SetTransactionDownloadedRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.fileId = fileId;
            return ((HAAD_TransactionChecker.HaaD.WebservicesSoap)(this)).SetTransactionDownloadedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HAAD_TransactionChecker.HaaD.GetPrescriptionsResponse HAAD_TransactionChecker.HaaD.WebservicesSoap.GetPrescriptions(HAAD_TransactionChecker.HaaD.GetPrescriptionsRequest request) {
            return base.Channel.GetPrescriptions(request);
        }
        
        public int GetPrescriptions(string login, string pwd, string payerID, string memberID, out byte[] prescription, out string errorMessage) {
            HAAD_TransactionChecker.HaaD.GetPrescriptionsRequest inValue = new HAAD_TransactionChecker.HaaD.GetPrescriptionsRequest();
            inValue.Body = new HAAD_TransactionChecker.HaaD.GetPrescriptionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.payerID = payerID;
            inValue.Body.memberID = memberID;
            HAAD_TransactionChecker.HaaD.GetPrescriptionsResponse retVal = ((HAAD_TransactionChecker.HaaD.WebservicesSoap)(this)).GetPrescriptions(inValue);
            prescription = retVal.Body.prescription;
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.GetPrescriptionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HAAD_TransactionChecker.HaaD.GetPrescriptionsResponse> HAAD_TransactionChecker.HaaD.WebservicesSoap.GetPrescriptionsAsync(HAAD_TransactionChecker.HaaD.GetPrescriptionsRequest request) {
            return base.Channel.GetPrescriptionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HAAD_TransactionChecker.HaaD.GetPrescriptionsResponse> GetPrescriptionsAsync(string login, string pwd, string payerID, string memberID) {
            HAAD_TransactionChecker.HaaD.GetPrescriptionsRequest inValue = new HAAD_TransactionChecker.HaaD.GetPrescriptionsRequest();
            inValue.Body = new HAAD_TransactionChecker.HaaD.GetPrescriptionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.payerID = payerID;
            inValue.Body.memberID = memberID;
            return ((HAAD_TransactionChecker.HaaD.WebservicesSoap)(this)).GetPrescriptionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HAAD_TransactionChecker.HaaD.AddDRGToEClaimResponse HAAD_TransactionChecker.HaaD.WebservicesSoap.AddDRGToEClaim(HAAD_TransactionChecker.HaaD.AddDRGToEClaimRequest request) {
            return base.Channel.AddDRGToEClaim(request);
        }
        
        public int AddDRGToEClaim(string login, string pwd, byte[] originalFileContent, string originalFileName, decimal baseRate, out byte[] drgFileContent, out string drgFileName, out byte[] auditFileContent, out byte[] reportFileContent, out string errorMessage, out byte[] errorReport) {
            HAAD_TransactionChecker.HaaD.AddDRGToEClaimRequest inValue = new HAAD_TransactionChecker.HaaD.AddDRGToEClaimRequest();
            inValue.Body = new HAAD_TransactionChecker.HaaD.AddDRGToEClaimRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.originalFileContent = originalFileContent;
            inValue.Body.originalFileName = originalFileName;
            inValue.Body.baseRate = baseRate;
            HAAD_TransactionChecker.HaaD.AddDRGToEClaimResponse retVal = ((HAAD_TransactionChecker.HaaD.WebservicesSoap)(this)).AddDRGToEClaim(inValue);
            drgFileContent = retVal.Body.drgFileContent;
            drgFileName = retVal.Body.drgFileName;
            auditFileContent = retVal.Body.auditFileContent;
            reportFileContent = retVal.Body.reportFileContent;
            errorMessage = retVal.Body.errorMessage;
            errorReport = retVal.Body.errorReport;
            return retVal.Body.AddDRGToEClaimResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HAAD_TransactionChecker.HaaD.AddDRGToEClaimResponse> HAAD_TransactionChecker.HaaD.WebservicesSoap.AddDRGToEClaimAsync(HAAD_TransactionChecker.HaaD.AddDRGToEClaimRequest request) {
            return base.Channel.AddDRGToEClaimAsync(request);
        }
        
        public System.Threading.Tasks.Task<HAAD_TransactionChecker.HaaD.AddDRGToEClaimResponse> AddDRGToEClaimAsync(string login, string pwd, byte[] originalFileContent, string originalFileName, decimal baseRate) {
            HAAD_TransactionChecker.HaaD.AddDRGToEClaimRequest inValue = new HAAD_TransactionChecker.HaaD.AddDRGToEClaimRequest();
            inValue.Body = new HAAD_TransactionChecker.HaaD.AddDRGToEClaimRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.originalFileContent = originalFileContent;
            inValue.Body.originalFileName = originalFileName;
            inValue.Body.baseRate = baseRate;
            return ((HAAD_TransactionChecker.HaaD.WebservicesSoap)(this)).AddDRGToEClaimAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HAAD_TransactionChecker.HaaD.CheckForNewPriorAuthorizationTransactionsResponse HAAD_TransactionChecker.HaaD.WebservicesSoap.CheckForNewPriorAuthorizationTransactions(HAAD_TransactionChecker.HaaD.CheckForNewPriorAuthorizationTransactionsRequest request) {
            return base.Channel.CheckForNewPriorAuthorizationTransactions(request);
        }
        
        public int CheckForNewPriorAuthorizationTransactions(string login, string pwd, out string errorMessage) {
            HAAD_TransactionChecker.HaaD.CheckForNewPriorAuthorizationTransactionsRequest inValue = new HAAD_TransactionChecker.HaaD.CheckForNewPriorAuthorizationTransactionsRequest();
            inValue.Body = new HAAD_TransactionChecker.HaaD.CheckForNewPriorAuthorizationTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            HAAD_TransactionChecker.HaaD.CheckForNewPriorAuthorizationTransactionsResponse retVal = ((HAAD_TransactionChecker.HaaD.WebservicesSoap)(this)).CheckForNewPriorAuthorizationTransactions(inValue);
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.CheckForNewPriorAuthorizationTransactionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HAAD_TransactionChecker.HaaD.CheckForNewPriorAuthorizationTransactionsResponse> HAAD_TransactionChecker.HaaD.WebservicesSoap.CheckForNewPriorAuthorizationTransactionsAsync(HAAD_TransactionChecker.HaaD.CheckForNewPriorAuthorizationTransactionsRequest request) {
            return base.Channel.CheckForNewPriorAuthorizationTransactionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HAAD_TransactionChecker.HaaD.CheckForNewPriorAuthorizationTransactionsResponse> CheckForNewPriorAuthorizationTransactionsAsync(string login, string pwd) {
            HAAD_TransactionChecker.HaaD.CheckForNewPriorAuthorizationTransactionsRequest inValue = new HAAD_TransactionChecker.HaaD.CheckForNewPriorAuthorizationTransactionsRequest();
            inValue.Body = new HAAD_TransactionChecker.HaaD.CheckForNewPriorAuthorizationTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            return ((HAAD_TransactionChecker.HaaD.WebservicesSoap)(this)).CheckForNewPriorAuthorizationTransactionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HAAD_TransactionChecker.HaaD.GetNewPriorAuthorizationTransactionsResponse HAAD_TransactionChecker.HaaD.WebservicesSoap.GetNewPriorAuthorizationTransactions(HAAD_TransactionChecker.HaaD.GetNewPriorAuthorizationTransactionsRequest request) {
            return base.Channel.GetNewPriorAuthorizationTransactions(request);
        }
        
        public int GetNewPriorAuthorizationTransactions(string login, string pwd, out string foundTransactions, out string errorMessage) {
            HAAD_TransactionChecker.HaaD.GetNewPriorAuthorizationTransactionsRequest inValue = new HAAD_TransactionChecker.HaaD.GetNewPriorAuthorizationTransactionsRequest();
            inValue.Body = new HAAD_TransactionChecker.HaaD.GetNewPriorAuthorizationTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            HAAD_TransactionChecker.HaaD.GetNewPriorAuthorizationTransactionsResponse retVal = ((HAAD_TransactionChecker.HaaD.WebservicesSoap)(this)).GetNewPriorAuthorizationTransactions(inValue);
            foundTransactions = retVal.Body.foundTransactions;
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.GetNewPriorAuthorizationTransactionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HAAD_TransactionChecker.HaaD.GetNewPriorAuthorizationTransactionsResponse> HAAD_TransactionChecker.HaaD.WebservicesSoap.GetNewPriorAuthorizationTransactionsAsync(HAAD_TransactionChecker.HaaD.GetNewPriorAuthorizationTransactionsRequest request) {
            return base.Channel.GetNewPriorAuthorizationTransactionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HAAD_TransactionChecker.HaaD.GetNewPriorAuthorizationTransactionsResponse> GetNewPriorAuthorizationTransactionsAsync(string login, string pwd) {
            HAAD_TransactionChecker.HaaD.GetNewPriorAuthorizationTransactionsRequest inValue = new HAAD_TransactionChecker.HaaD.GetNewPriorAuthorizationTransactionsRequest();
            inValue.Body = new HAAD_TransactionChecker.HaaD.GetNewPriorAuthorizationTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            return ((HAAD_TransactionChecker.HaaD.WebservicesSoap)(this)).GetNewPriorAuthorizationTransactionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HAAD_TransactionChecker.HaaD.GetDRGDetailsResponse HAAD_TransactionChecker.HaaD.WebservicesSoap.GetDRGDetails(HAAD_TransactionChecker.HaaD.GetDRGDetailsRequest request) {
            return base.Channel.GetDRGDetails(request);
        }
        
        public int GetDRGDetails(string login, string pwd, string xmlClaimInput, out string xmlDRGDetails, out byte[] auditFileContent, out byte[] reportFileContent, out string errorMessage) {
            HAAD_TransactionChecker.HaaD.GetDRGDetailsRequest inValue = new HAAD_TransactionChecker.HaaD.GetDRGDetailsRequest();
            inValue.Body = new HAAD_TransactionChecker.HaaD.GetDRGDetailsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.xmlClaimInput = xmlClaimInput;
            HAAD_TransactionChecker.HaaD.GetDRGDetailsResponse retVal = ((HAAD_TransactionChecker.HaaD.WebservicesSoap)(this)).GetDRGDetails(inValue);
            xmlDRGDetails = retVal.Body.xmlDRGDetails;
            auditFileContent = retVal.Body.auditFileContent;
            reportFileContent = retVal.Body.reportFileContent;
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.GetDRGDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HAAD_TransactionChecker.HaaD.GetDRGDetailsResponse> HAAD_TransactionChecker.HaaD.WebservicesSoap.GetDRGDetailsAsync(HAAD_TransactionChecker.HaaD.GetDRGDetailsRequest request) {
            return base.Channel.GetDRGDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HAAD_TransactionChecker.HaaD.GetDRGDetailsResponse> GetDRGDetailsAsync(string login, string pwd, string xmlClaimInput) {
            HAAD_TransactionChecker.HaaD.GetDRGDetailsRequest inValue = new HAAD_TransactionChecker.HaaD.GetDRGDetailsRequest();
            inValue.Body = new HAAD_TransactionChecker.HaaD.GetDRGDetailsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.xmlClaimInput = xmlClaimInput;
            return ((HAAD_TransactionChecker.HaaD.WebservicesSoap)(this)).GetDRGDetailsAsync(inValue);
        }
    }
}
